# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="ys"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
  extract
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"
export PATH="/home/scratch.stdeng_inf/anaconda3/bin":"/home/scratch.stdeng_inf/anaconda3/envs":"/home/utils/tmux-2.8/bin":$PATH

#export PATH="/home/tools/continuum/Anaconda3-5.1.0/bin":$PATH



#export PATH="/home/xind/vulkan/1.1.85.0/x86_64/bin":"/usr/sbin":"/home/xind/anaconda3/bin":$PATH
#export PATH="/home/xind/vulkan/1.1.92.1/x86_64/bin":"/home/xind/anaconda3/bin":$PATH
#export VULKAN_SDK="/home/xind/vulkan/1.1.92.1/x86_64" 
#export LD_LIBRARY_PATH="/mnt/disk/charles/work/perfinspector/pic-v/libs":"/home/xind/vulkan/1.1.85.0/x86_64/lib":"/usr/local/lib":$LD_LIBRARY_PATH

#export LD_LIBRARY_PATH="/mnt/disk/charles/work/perfinspector/pic-v/libs":"/home/xind/vulkan/1.1.92.1/x86_64/lib":$LD_LIBRARY_PATH
#export VK_LAYER_PATH="/home/xind/vulkan/1.1.85.0/x86_64/etc/explicit_layer.d"
#export VK_LAYER_PATH="/mnt/disk/charles/works/perfinspector/pic-v/bin"
#export P4_HW="/mnt/disk/charles/works/perfinspector/pic-v"

#layer
#export VK_INSTANCE_LAYERS=VK_LAYER_NV_PerfInspectorVK

#p4
#export P4USER=stdeng
#export P4CLIENT=p4_stdeng_hw
#export P4PORT=p4proxy-zj:2001

#cuda
#export PATH="/usr/local/cuda-10.0/bin":$PATH
#export LD_LIBRARY_PATH="/usr/local/cuda-10.0/lib64":$LD_LIBRARY_PATH

#pic-c
#export PATH="/path/to/pic-c":$PATH


# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
. /home/stdeng/.autojump/etc/profile.d/autojump.sh 
#. /usr/share/autojump/autojump.sh
#export GOPATH=$HOME/go
#export PATH=${PATH}:${GOPATH}/bin
#

if [ -f ~/.shellrc ]; then
    . ~/.shellrc
fi
